
services:
  db:
    image: postgres:15
    container_name: shonendle-db
    environment:
      POSTGRES_USER: roica
      POSTGRES_PASSWORD: roicalamar
      POSTGRES_DB: shonendle
   
    volumes:
      - shonendle-data:/var/lib/postgresql/data
      - ./backend/db/data:/docker-entrypoint-initdb.d/backend/db/script/create.sql

  backend:
    build: ./backend
    command: node index.js
    volumes:
      - ./backend:/app
    environment:
      DB_USER: roica
      DB_PASSWORD: roicalamar
      DB_NAME: shonendle
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
    ports:
      - "3000:3000"

volumes:
  shonendle-data: